# Generated by Django 5.2.6 on 2025-09-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_registroprueba_socio_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
